### ISSUE TITLE
file encryption 

### ISSUE THREAD

**Issue by tomShoutTheSecond** [tomShoutTheSecond/SiaTesting#23]
key pair generation for a connection between two specific devices

copy the key to the other device so it can decrypt files sent by the other device

**Comment by jacobh-gh** [comment]
[SkySend](https://github.com/redsolver/skysend) does this by sending a URL with the decryption key. However, I think the app should support sending files over SkyNet without sending a URL via a messaging app, because doing it that way kind of negates the privacy benefit of using Sia backend.

One way will be to pair devices, so that they can upload files to a Skylink which both clients would have access to the SkyDB entry for (as you suggested yesterday). If we add this, let's also add pairing by QR code as an option for mobile users.

There was talk of a SkyDB message service, if that can do PNs on mobile it would be a great feature to add when receiving files or a pairing request.
